# docker-compose.yml to start app and a redis server

version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=!!!redis!!

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass "!!!redis!!"
    ports:
     - "6379:6379"
