# docker-compose.yml to start app and a redis server

version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
